//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SoapService.opendap.co_ops.nos.noaa.gov {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="highlowtidepredSoapBinding", Namespace="https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl")]
    public partial class highlowtidepredService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getHighLowTidePredictionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHLPredAndMetadataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public highlowtidepredService() {
            this.Url = global::SoapService.Properties.Settings.Default.SoapPractice_opendap_co_ops_nos_noaa_gov_highlowtidepredService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getHighLowTidePredictionsCompletedEventHandler getHighLowTidePredictionsCompleted;
        
        /// <remarks/>
        public event getHLPredAndMetadataCompletedEventHandler getHLPredAndMetadataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("HighLowValues", Namespace="https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl")]
        public HighLowValues getHighLowTidePredictions([System.Xml.Serialization.XmlElementAttribute(Namespace="https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl")] Parameters Parameters) {
            object[] results = this.Invoke("getHighLowTidePredictions", new object[] {
                        Parameters});
            return ((HighLowValues)(results[0]));
        }
        
        /// <remarks/>
        public void getHighLowTidePredictionsAsync(Parameters Parameters) {
            this.getHighLowTidePredictionsAsync(Parameters, null);
        }
        
        /// <remarks/>
        public void getHighLowTidePredictionsAsync(Parameters Parameters, object userState) {
            if ((this.getHighLowTidePredictionsOperationCompleted == null)) {
                this.getHighLowTidePredictionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHighLowTidePredictionsOperationCompleted);
            }
            this.InvokeAsync("getHighLowTidePredictions", new object[] {
                        Parameters}, this.getHighLowTidePredictionsOperationCompleted, userState);
        }
        
        private void OngetHighLowTidePredictionsOperationCompleted(object arg) {
            if ((this.getHighLowTidePredictionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHighLowTidePredictionsCompleted(this, new getHighLowTidePredictionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("HighLowAndMetadata", Namespace="https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl")]
        public HighLowAndMetadata getHLPredAndMetadata([System.Xml.Serialization.XmlElementAttribute(Namespace="https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl")] Parameters Parameters) {
            object[] results = this.Invoke("getHLPredAndMetadata", new object[] {
                        Parameters});
            return ((HighLowAndMetadata)(results[0]));
        }
        
        /// <remarks/>
        public void getHLPredAndMetadataAsync(Parameters Parameters) {
            this.getHLPredAndMetadataAsync(Parameters, null);
        }
        
        /// <remarks/>
        public void getHLPredAndMetadataAsync(Parameters Parameters, object userState) {
            if ((this.getHLPredAndMetadataOperationCompleted == null)) {
                this.getHLPredAndMetadataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHLPredAndMetadataOperationCompleted);
            }
            this.InvokeAsync("getHLPredAndMetadata", new object[] {
                        Parameters}, this.getHLPredAndMetadataOperationCompleted, userState);
        }
        
        private void OngetHLPredAndMetadataOperationCompleted(object arg) {
            if ((this.getHLPredAndMetadataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHLPredAndMetadataCompleted(this, new getHLPredAndMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl")]
    public partial class Parameters {
        
        private string stationIdField;
        
        private string beginDateField;
        
        private string endDateField;
        
        private string datumField;
        
        private int unitField;
        
        private int timeZoneField;
        
        /// <remarks/>
        public string stationId {
            get {
                return this.stationIdField;
            }
            set {
                this.stationIdField = value;
            }
        }
        
        /// <remarks/>
        public string beginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
            }
        }
        
        /// <remarks/>
        public int unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public int timeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl")]
    public partial class highlowtidepred {
        
        private string timeField;
        
        private double predField;
        
        private string typeField;
        
        /// <remarks/>
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public double pred {
            get {
                return this.predField;
            }
            set {
                this.predField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl")]
    public partial class Data {
        
        private highlowtidepred[] dataField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data")]
        public highlowtidepred[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl")]
    public partial class HighLowValues {
        
        private Data[] highLowValues1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("HighLowValues", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public Data[] HighLowValues1 {
            get {
                return this.highLowValues1Field;
            }
            set {
                this.highLowValues1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://opendap.co-ops.nos.noaa.gov/axis/webservices/highlowtidepred/wsdl")]
    public partial class HighLowAndMetadata {
        
        private string stationIdField;
        
        private string stationNameField;
        
        private float latitudeField;
        
        private float longitudeField;
        
        private string stateField;
        
        private string dataSourceField;
        
        private string cOOPSDisclaimerField;
        
        private string beginDateField;
        
        private string endDateField;
        
        private string datumField;
        
        private string unitField;
        
        private string timeZoneField;
        
        private Data[] highLowValuesField;
        
        /// <remarks/>
        public string stationId {
            get {
                return this.stationIdField;
            }
            set {
                this.stationIdField = value;
            }
        }
        
        /// <remarks/>
        public string stationName {
            get {
                return this.stationNameField;
            }
            set {
                this.stationNameField = value;
            }
        }
        
        /// <remarks/>
        public float latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public float longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string dataSource {
            get {
                return this.dataSourceField;
            }
            set {
                this.dataSourceField = value;
            }
        }
        
        /// <remarks/>
        public string COOPSDisclaimer {
            get {
                return this.cOOPSDisclaimerField;
            }
            set {
                this.cOOPSDisclaimerField = value;
            }
        }
        
        /// <remarks/>
        public string beginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
            }
        }
        
        /// <remarks/>
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string datum {
            get {
                return this.datumField;
            }
            set {
                this.datumField = value;
            }
        }
        
        /// <remarks/>
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public string timeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public Data[] HighLowValues {
            get {
                return this.highLowValuesField;
            }
            set {
                this.highLowValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getHighLowTidePredictionsCompletedEventHandler(object sender, getHighLowTidePredictionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHighLowTidePredictionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHighLowTidePredictionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HighLowValues Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HighLowValues)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getHLPredAndMetadataCompletedEventHandler(object sender, getHLPredAndMetadataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHLPredAndMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHLPredAndMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HighLowAndMetadata Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HighLowAndMetadata)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591